<?php

namespace App\Classes;

class OurRedisQueue extends RedisQueue
{
    public function push($job, $data = '', $queue = null)
    {
        return parent::push($job, $data, $queue); // TODO: Change the autogenerated stub
    }

}